### ISSUE TITLE
about preprocess data

### ISSUE THREAD

**Issue by yihaoyao402** [keonlee9420/DiffSinger#5]
hi, thanks for your work. but i met a problem in diffsinger and diffgan both
Traceback (most recent call last):
  File "F:\DiffSinger-main\preprocess.py", line 19, in <module>
    preprocessor.build_from_path()
  File "F:\DiffSinger-main\preprocessor\preprocessor.py", line 113, in build_from_path
    if len(f0) > 0:
UnboundLocalError: local variable 'f0' referenced before assignment
it bothers me a lot, thanks for your help

**Comment by yihaoyao402** [comment]
@keonlee9420
